; Cries indexes (see audio/cry_pointers.asm)
	const_def

; gen 1
	const CRY_NIDORAN_M
	const CRY_NIDORAN_F
	const CRY_SLOWPOKE
	const CRY_KANGASKHAN
	const CRY_CHARMANDER
	const CRY_GRIMER
	const CRY_VOLTORB
	const CRY_MUK
	const CRY_ODDISH
	const CRY_RAICHU
	const CRY_NIDOQUEEN
	const CRY_DIGLETT
	const CRY_WINGULL
	const CRY_DROWZEE
	const CRY_ROOKIDEE
	const CRY_BULBASAUR
	const CRY_SPEAROW
	const CRY_RHYDON
	const CRY_GOLEM
	const CRY_BLASTOISE
	const CRY_PIDGEOTTO
	const CRY_WEEDLE
	const CRY_CATERPIE
	const CRY_EKANS
	const CRY_FEAROW
	const CRY_CLEFAIRY
	const CRY_SNOM
	const CRY_LAPRAS
	const CRY_METAPOD
	const CRY_SQUIRTLE
	const CRY_PARAS
	const CRY_GROWLITHE
	const CRY_KRABBY
	const CRY_PSYDUCK
	const CRY_RATTATA
	const CRY_VILEPLUME
	const CRY_VULPIX
	const CRY_WEEPINBELL

; gen 2
	const CRY_MEDITITE
	const CRY_BARBOACH
	const CRY_TOGEPI
	const CRY_GIRAFARIG
	const CRY_ARCHETA
	const CRY_MAREEP
	const CRY_TOGETIC
	const CRY_HOOTHOOT
	const CRY_BUNEARY
	const CRY_SLOWKING
	const CRY_TORCHIC
	const CRY_TREECKO
	const CRY_MUDKIP
	const CRY_GLIGAR
	const CRY_LOMBRE
	const CRY_APPLIN
	const CRY_MUNNA
	const CRY_ENTEI
	const CRY_WOOPER
	const CRY_MANTINE
	const CRY_BLAZIKEN
	const CRY_NATU
	const CRY_COTTONEE
	const CRY_SUNFLORA
	const CRY_AMPHAROS
	const CRY_APPLETUN
	const CRY_LOTAD
	const CRY_MAGNELOCKE
	const CRY_DUNSPARCE
	const CRY_CREEPTURE

DEF NUM_CRIES EQU const_value
