FramesPointers:
	table_width 2, FramesPointers
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw CaterpieFrames
	dw MetapodFrames
	dw ButterfreeFrames
	dw WeedleFrames
	dw KakunaFrames
	dw BeedrillFrames
	dw RookideeFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw RattataFrames
	dw RaticateFrames
	dw SpearowFrames
	dw FearowFrames
	dw EkansFrames
	dw ArbokFrames
	dw PikachuFrames
	dw RaichuFrames
	dw SandshrewFrames
	dw SandslashFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw ParasFrames
	dw ParasectFrames
	dw SnomFrames
	dw SnomyomiFrames
	dw DiglettFrames
	dw DugtrioFrames
	dw MeowthFrames
	dw PersianFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw FarfetchDFrames
	dw DoduoFrames
	dw DodrioFrames
	dw WingullFrames
	dw PelipperFrames
	dw GrimerFrames
	dw MukFrames
	dw ShellderFrames
	dw CloysterFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw DrowzeeFrames
	dw HypnoFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw CuboneFrames
	dw MarowakFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw EmolgaFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw ChanseyFrames
	dw TangelaFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw CacneaFrames
	dw CacturneFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw ScytherFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw MewtwoFrames
	dw MewFrames
	dw TreeckoFrames
	dw GrovyleFrames
	dw SceptileFrames
	dw TorchicFrames
	dw CombuskenFrames
	dw BlazikenFrames
	dw MudkipFrames
	dw MarshtompFrames
	dw SwampertFrames
	dw BunearyFrames
	dw LopunnyFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw MunnaFrames
	dw MusharnaFrames
	dw PubbleFrames
	dw GubblerFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw LotadFrames
	dw LombreFrames
	dw LudicoloFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw MedititeFrames
	dw MedichamFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw MagnelockeFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingFrames
	dw MisdreavusFrames
	dw UnownFrames
	dw Gyarados_sFrames
	dw GirafarigFrames
	dw ShieldonFrames
	dw BastiodonFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw CranidosFrames
	dw RampardosFrames
	dw QwilfishFrames
	dw ScizorFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw CottoneeFrames
	dw WhimsicottFrames
	dw ApplinFrames
	dw AppletunFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaFrames
	dw Dudunsparce_TwoFrames
	dw Dudunsparce_ThreeFrames
	dw DelibirdFrames
	dw MantineFrames
	dw AudinoFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw MinkeyFrames
	dw CreeptureFrames
	dw Porygon2Frames
	dw StantlerFrames
	dw SmeargleFrames
	dw TyrogueFrames
	dw SylveonFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw ArchetaFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HogwyreFrames
	dw CelebiFrames
	dw MamoswineFrames
	assert_table_length NUM_POKEMON
